# Site settings
title: Identity
email: youremailaddress@gmail.com
description: The Jekyll version of the Identity theme by HTML5 UP.
baseurl: "/ryanstraits" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Ryan Straits
your-title: All Things Reconsidered

# Social settings
500px_url:
facebook_url: https://facebook.com
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/ryanstraits
linkedin_url: https://www.linkedin.com/in/ryanstraits
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ryanstraits

# Build settings
markdown: kramdown
